---
name: Vaultwarden (Bitwarden)
version: dev
slug: bitwarden
description: Open source password management solution
url: https://github.com/hassio-addons/addon-bitwarden
codenotary: codenotary@frenck.dev
webui: "[PROTO:ssl]://[HOST]:[PORT:7277]"
init: false
arch:
  - aarch64
  - amd64
  - armv7
ports:
  7277/tcp: 7277
ports_description:
  7277/tcp: Vaultwarden Web interface
map:
  - ssl
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
  request_size_limit: int?
  sso_enabled: bool?
  sso_authority: str?
  sso_client_id: str?
  sso_client_secret: password?
  sso_scopes": str?
  sso_allow_unknown_email_verification: bool?
  sso_client_cache_expiration: int?
  sso_only: bool?
  sso_signups_match_email: bool?
