---
version: "1.0.0"
slug: example-addon
name: Example Add-on Template
description: "A simple example Home Assistant add-on for development reference"
url: "https://github.com/ddcash/n1k0-addons/tree/main/example-addon"
arch:
  - aarch64
  - amd64
init: false
ingress: true
ingress_port: 8080
panel_icon: mdi:developer-board
panel_title: Example App
ports:
  8080/tcp: 8080
map:
  - config:ro
  - share:rw
options:
  message: "Hello World"
  log_level: info
schema:
  message: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?