---
name: VSCode with AI Development Tools
version: "1.1.0"
slug: vscode-claude
description: Visual Studio Code with Claude Code CLI and Gemini CLI integration for AI-powered development in Home Assistant.
url: https://github.com/ddcash/n1k0-addons/tree/main/vcode-ai
ingress: true
ingress_port: 1337
ingress_stream: true
panel_icon: mdi:microsoft-visual-studio-code
panel_title: VSCode AI
startup: services
init: false
arch:
  - aarch64
  - amd64
uart: true
hassio_api: true
hassio_role: manager
homeassistant_api: true
map:
  - type: addons
    read_only: false
  - type: all_addon_configs
    read_only: false
  - type: backup
    read_only: false
  - type: homeassistant_config
    read_only: false
    path: /config
  - type: media
    read_only: false
  - type: share
    read_only: false
  - type: ssl
    read_only: false
services:
  - mysql:want
  - mqtt:want
options:
  packages: []
  init_commands: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  config_path: str?
  packages:
    - str
  init_commands:
    - str
